title:Amrita Kaur
#logo:/
Description:I am passionate about staying at the forefront of industry trends and continuously improving BI processes to meet the evolving needs of organizations. My strong analytical mindset, combined with excellent communication and stakeholder management skills, enables me to bridge the gap between technical and non-technical teams, driving collaboration and achieving project success.
show_download:true
theme:jekyll-theme-minimal
